"""add_is_archived_to_tickets

Revision ID: 583a3db48731
Revises: initial_migration
Create Date: 2025-03-28 16:55:02.470494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583a3db48731'
down_revision: Union[str, None] = 'initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_tickets_is_archived'), 'tickets', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_is_archived'), table_name='tickets')
    op.drop_column('tickets', 'is_archived')
    # ### end Alembic commands ###